org: robertoseba
app: latam-aws
service: latam-aws-sls

useDotenv: true

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    EMAIL_FROM: ${env:EMAIL_FROM}
    EMAIL_TO: ${env:EMAIL_TO}
    MAX_PRICE: ${env:MAX_PRICE}
    MAX_DAYS: ${env:MAX_DAYS}
    MIN_DAYS: ${env:MIN_DAYS}
    INITIAL_DATE: ${env:INITIAL_DATE}
    ORIGIN: ${env:ORIGIN}
    DESTINATION: ${env:DESTINATION}

functions:
  findTickets:
    handler: src/handler.run
    events:
      - schedule: cron(0 6 ? * MON,WED,SAT *)
    timeout: 300

plugins:
  - serverless-esbuild
  - serverless-offline
